class Netflix {


	static String Top10Movies[] = {"Mea Culpa","Ruby Gillman, Teenage Kraken","The Abyss","Thanksgiving","The Super Mario Bros. Movie","Players","Lover, Stalker, Killer","Einstein and the Bomb ","Trolls","Code 8"};
	static String EnglishMovies[] = {"Ali","American Graffiti","Burning","Everything Everywhere All at Once","Frances Ha","Glass Onion: A Knives Out Mystery","Godzilla Minus One","Hit Man","Homecoming","Hulk","It Follows","The Killer","King Richard","Living","Marcel the Shell With Shoes On","Marriage Story","May December","Molly’s Game","The Nest","No Hard Feelings","Oldboy","Shrek","Something’s Gotta Give","RRR","The Woman King"};
	static String KannadaMovies[] = {"Kantara","777 Charlie","KGF Chapter 2","Vikranth Rona","James","Gaalipata 2","Old Monk","Guru Shishyaru","Avatara Purusha","Ek Love Ya","Love Mocktail 2","Window Seat","Petromax","Harikathe Alla Girikathe","Family Pack","Case Of Kondana","Blink","Ondu Sarala Premakathe","Kerebete","Shakhahaari","Yuva","O2","Grey Games","KGF","Mungaaru Male"};
	static String HindiMovies[] = {" The Lunchbox","Zindagi Na Milegi Dobara","Yeh Jawaani Hai Deewani"," Taare Zameen Par "," Barfi","Swades","Wake Up Sid","Special 26 ","Queen ","Drishyam ","Pink ","Baahubali"," PK "," Masaan","Sanju"," No One Killed Jessica"," Mimi"," Bareilly ki Barfi ","Pad Man"," Mom ","Udta Punjab","Dear Zindagi","Madras Cafe","Margarita With A Straw","Kabir Singh"};
	static String KoreanSeries[] = {"Crash Landing on You ","Crash Landing on Me ","Squid Game","Kingdom","Hellbound","Our Beloved Summer","Boys Over Flowers ","A Killer Paradox","Parasyte: The Grey","Business Proposal","All of Us Are Dead","D.P.","Physical: 100","Twenty-Five Twenty-One","It's Okay to Not Be Okay","Hometown Cha-Cha-Cha ","Little Women","Mr. Sunshine","Sweet Home","A Time Called You","Crash Landing on You","Extraordinary Attorney Woo","Goblin",",My Demon","When I fly Towards You"};
	
	
public static void main(String[] newCollection){
	
	System.out.println("The Available Top10Movies are:"+Top10Movies[0]+" , "+Top10Movies[1]+" , "+Top10Movies[2]+" , "+Top10Movies[3]+" , "+Top10Movies[4]+" , "+Top10Movies[5]+" , "+Top10Movies[6]+" , "+Top10Movies[7]+" , "+Top10Movies[8]+" , "+Top10Movies[9]+" . ");
	System.out.println("The Available EnglishMovies are:"+EnglishMovies[0]+" , "+EnglishMovies[1]+" , "+EnglishMovies[2]+" , "+EnglishMovies[3]+" , "+EnglishMovies[4]+" , "+EnglishMovies[5]+" , "+EnglishMovies[6]+" , "+EnglishMovies[7]+" , "+EnglishMovies[8]+" , "+EnglishMovies[9]+" , "+EnglishMovies[10]+" , "+EnglishMovies[11]+" , "+EnglishMovies[12]+" , "+EnglishMovies[13]+" , "+EnglishMovies[14]+" , "+EnglishMovies[15]+" , "+EnglishMovies[16]+" , "+EnglishMovies[17]+" , "+EnglishMovies[18]+" , "+EnglishMovies[19]+" , "+EnglishMovies[20]+" , "+EnglishMovies[21]+" , "+EnglishMovies[22]+" , "+EnglishMovies[23]+" , "+EnglishMovies[24]+ " . ");
	System.out.println("The Available KannadaMovies are:"+KannadaMovies[0]+" , "+KannadaMovies[1]+" , "+KannadaMovies[2]+" , "+KannadaMovies[3]+" , "+KannadaMovies[4]+" , "+KannadaMovies[5]+" , "+KannadaMovies[6]+" , "+KannadaMovies[7]+" , "+KannadaMovies[8]+" , "+KannadaMovies[9]+" , "+KannadaMovies[10]+" , "+KannadaMovies[11]+" , "+KannadaMovies[12]+" , "+KannadaMovies[13]+" , "+KannadaMovies[14]+" , "+KannadaMovies[15]+" , "+KannadaMovies[16]+" , "+KannadaMovies[17]+" , "+KannadaMovies[18]+" , "+KannadaMovies[19]+" , "+KannadaMovies[20]+" , "+KannadaMovies[21]+" , "+KannadaMovies[22]+" , "+KannadaMovies[23]+" , "+KannadaMovies[24]+ " . ");
	System.out.println("The Available HindiMovies are:"+HindiMovies[0]+" , "+HindiMovies[1]+" , "+HindiMovies[2]+" , "+HindiMovies[3]+" , "+HindiMovies[4]+" , "+HindiMovies[5]+" , "+HindiMovies[6]+" , "+HindiMovies[7]+" , "+HindiMovies[8]+" , "+HindiMovies[9]+" , "+HindiMovies[10]+" , "+HindiMovies[11]+" , "+HindiMovies[12]+" , "+HindiMovies[13]+" , "+HindiMovies[14]+" , "+HindiMovies[15]+" , "+HindiMovies[16]+" , "+HindiMovies[17]+" , "+HindiMovies[18]+" , "+HindiMovies[19]+" , "+HindiMovies[20]+" , "+HindiMovies[21]+" , "+HindiMovies[22]+" , "+HindiMovies[23]+" , "+HindiMovies[24]+ " . ");
	System.out.println("The Available KoreanSeries are:"+KoreanSeries[0]+" , "+KoreanSeries[1]+" , "+KoreanSeries[2]+" , "+KoreanSeries[3]+" , "+KoreanSeries[4]+" , "+KoreanSeries[5]+" , "+KoreanSeries[6]+" , "+KoreanSeries[7]+" , "+KoreanSeries[8]+" , "+KoreanSeries[9]+" , "+KoreanSeries[10]+" , "+KoreanSeries[11]+" , "+KoreanSeries[12]+" , "+KoreanSeries[13]+" , "+KoreanSeries[14]+" , "+KoreanSeries[15]+" , "+KoreanSeries[16]+" , "+KoreanSeries[17]+" , "+KoreanSeries[18]+" , "+KoreanSeries[19]+" , "+KoreanSeries[20]+" , "+KoreanSeries[21]+" , "+KoreanSeries[22]+" , "+KoreanSeries[23]+" , "+KoreanSeries[24]+" . ");
	
}
} 